# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=16)),
                ('nickname', models.CharField(max_length=16)),
                ('register_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=16)),
                ('comment', models.CharField(max_length=255)),
                ('comment_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_name', models.CharField(max_length=64)),
                ('pic_url', models.URLField()),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('user_num', models.CharField(max_length=64)),
                ('times', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TestModel2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('leijiyaoqing_yh', models.CharField(max_length=64)),
                ('xinzengyaoqing_yh', models.CharField(max_length=64)),
                ('leijiduihuan_kc', models.CharField(max_length=64)),
                ('xinzengduihuan', models.CharField(max_length=64)),
                ('leiji_kcyh', models.CharField(max_length=64)),
                ('xinzeng_kcyh', models.CharField(max_length=64)),
                ('v', models.CharField(max_length=64)),
            ],
        ),
    ]
