# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_name', models.CharField(max_length=64)),
                ('pic_url', models.URLField()),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
