# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('user_num', models.CharField(max_length=64)),
                ('times', models.CharField(max_length=64)),
            ],
        ),
    ]
