# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_testmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('leijiyaoqing_yh', models.CharField(max_length=64)),
                ('xinzengyaoqing_yh', models.CharField(max_length=64)),
                ('leijiduihuan_kc', models.CharField(max_length=64)),
                ('xinzengduihuan', models.CharField(max_length=64)),
                ('leiji_kcyh', models.CharField(max_length=64)),
                ('xinzeng_kcyh', models.CharField(max_length=64)),
                ('v', models.CharField(max_length=64)),
            ],
        ),
    ]
