# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_pictures'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=16)),
                ('nickname', models.CharField(max_length=16)),
                ('register_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
