# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20170831_0615'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('school', models.CharField(max_length=255)),
            ],
        ),
    ]
