# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 03:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_accounts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
